workflows:
  ios-native-quick-start:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: "Code Magic" 
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: sina.QuranTranslation
      vars:
        BUNDLE_ID: "sina.QuranTranslation"
        XCODE_WORKSPACE: "QuranSearch.xcworkspace"
        XCODE_SCHEME: "QuranSearch"
        XCODE_PROJECT: "QuranSearch"
        APP_ID: 1659904084
      xcode: latest
      cocoapods: default
    triggering:
      tag_patterns:                 # Include or exclude watched tag labels
        - pattern: '*'
          include: true
      cancel_previous_builds: false  # Set to `true` to automatically cancel outdated webhook builds
    scripts:
      - name: Exit build if [upload dev] not included
        script: | 
          set -e
          set -x
          export COMMIT_MSG=$(git log -1 --pretty=%B)
          echo COMMIT_MSG
          if [[ $COMMIT_MSG != *"[upload dev]"* ]]
            then
              echo "Commit does not want to be tested"
              exit 1
            else 
              echo "Commit message includes '[upload dev]', moving forward..."
          fi
    publishing:
      email:
        recipients:
          - sina.hime009@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
