name: SwiftLint code

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlinting.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      - '.scripts/swiftlint'
      - '.scripts/swiftlint-changes'

jobs:
  SwiftLint:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Swiftlint Check
        run: chmod +x .scripts/swiftlint-changes; .scripts/swiftlint-changes --compare origin/${{ github.head_ref }} origin/${{ github.base_ref }}
        