name: SwiftLint code

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlinting.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      - '.scripts/swiftlint'
      - '.scripts/swiftlint-changes'

jobs:
  SwiftLint:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Swiftlint Check
        run: echo $(git branch); chmod +x .scripts/swiftlint-changes; .scripts/swiftlint-changes --compare ${{ github.head_ref }} ${{ github.base_ref }}
        